<?php

/**
 * @file
 * Core HWJMA Site module
 */
use Drupal\node\Entity\NodeType;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Url;
use Drupal\highwire_content\HighWireContent;
use Drupal\views\Plugin\views\query\QueryPluginBase;
use Drupal\views\ViewExecutable;


function hwjma_monsido_page_attachments_alter(array &$page) {
  // JOCREX-356: adding jS for cookiee module 
  $page['#attached']['library'][] = 'hwjma_monsido/monsidojs';
}