<?php

use Drupal\Core\Render\BubbleableMetadata;

/**
 * Implements hook_theme().
 */
function hwjma_ecommerce_theme() {
  return [
    'hwjma_access_panel' => [
      'template' => 'hwjma-access-panel',
      'variables' => ['user_access' => FALSE, 'user_access_already' => [], 'pricing_items' => [], 'purchase_children' => [], 'access_content_type' => ''],
    ],
    'hwjma_purchase_offer' => [
      'template' => 'hwjma-purchase-offer',
      'variables' => ['product' => [], 'purchase_offers' => [], 'purchase_link' => ''],
    ],
    'hwjma_purchase_offer_item' => [
      'template' => 'hwjma-purchase-offer-item',
      'variables' => ['type' => '', 'duration' => '', 'purchase_link' => ''],
    ],
  ];
}

/**
 * Implements template_preprocess_THEME().
 */
function template_preprocess_hwjma_access_panel(&$variables) {
  $variables['attributes']['class'][] = 'hwjma-access-panel';
  $variables['attributes']['class'][] = !empty($variables['user_access']) ? 'user-access' : 'user-no-access';
}

/**
 * Implements template_preprocess_THEME().
 */
function template_preprocess_hwjma_purchase_offer(&$variables) {
  $variables['attributes']['class'][] = 'hwjma-purchase-offer';
  $variables['attributes']['class'][] = 'product';
}

/**
 * Implements template_preprocess_THEME().
 */
function template_preprocess_hwjma_purchase_offer_item(&$variables) {
  // Add access label & info text based on type.
  if (!empty($variables['type'])) {
    switch ($variables['type']) {
      case 'perpetual':
        $variables['label'] = t('Perpetual access');
        $variables['info'] = t('You will have access to this version of the content. Future versions may not be covered.');
        break;
      case 'rental':
        $variables['label'] = !empty($variables['duration']) ? $variables['duration'] : t('Rental access');
        $variables['info'] = t('You will have access to this content for the specified period, including any updates during that period.');
        break;
    }
  }
}

/**
 * Implements hook_library_info_build().
 */
function hwjma_ecommerce_library_info_alter(&$libraries, $extension) {
  // Add hwjma_ecommerce/hwjma_ecommerce as a dependency of highwire_ecommerce/highwire_ecommerce_foxycart.
  if ($extension == 'highwire_ecommerce') {
    if (isset($libraries['highwire_ecommerce_foxycart'])) {
      // @see hwjma_ecommerce_js_alter().
      $libraries['highwire_ecommerce_foxycart']['dependencies'][] = 'hwjma_ecommerce/hwjma_ecommerce';
    }
  }
}

/**
 * Implements hook_js_alter().
 */
function hwjma_ecommerce_js_alter(&$javascript, $assets) {
  // Ensure hwjma_ecommerce/hwjma_ecommerce gets loaded after highwire_ecommerce/highwire_ecommerce_foxycart.
  // @TODO: remove when https://www.drupal.org/node/1945262 gets released.
  $lib_discovery = \Drupal::service('library.discovery');

  // Look up paths to js files from library definition.
  $hw_ecom_foxycart_lib = $lib_discovery->getLibraryByName('highwire_ecommerce', 'highwire_ecommerce_foxycart');
  $hwjma_ecom_lib = $lib_discovery->getLibraryByName('hwjma_ecommerce', 'hwjma_ecommerce');
  $hw_ecom_foxycart_js = !empty($hw_ecom_foxycart_lib['js'][0]['data']) ? $hw_ecom_foxycart_lib['js'][0]['data'] : '';
  $hwjma_ecom_js = !empty($hwjma_ecom_lib['js'][0]['data']) ? $hwjma_ecom_lib['js'][0]['data'] : '';

  // Set weight of hwjma_ecommerce/hwjma_ecommerce to just higher than highwire_ecommerce/highwire_ecommerce_foxycart
  if (!empty($javascript[$hw_ecom_foxycart_js]) && !empty($javascript[$hwjma_ecom_js])) {
    $javascript[$hwjma_ecom_js]['weight'] = $javascript[$hw_ecom_foxycart_js]['weight'] + 0.001;
    
  }
}

/**
* Helper function to get book chunk content types for the MHE site.
*
* @return array
*   Array of book chunk node types
*/
function hwjma_core_get_book_chunk_types() {
  return ['item_chapter', 'item_section','item_front_matter', 'item_back_matter'];
}

/**
* Helper function to get journal chunk content types for the bps site.
*
* @return array
*   journal chunk node types
*/
function hwjma_core_get_journal_chunk_types() {
  return ['journal_article', 'journal_issue', 'journal_volume', 'journal_fragment'];
}

/**
* Implements hook_tokens().
*/
function hwjma_core_tokens($type, array $tokens, array $data, array $options, BubbleableMetadata $bubbleable_metadata) {
  $replacements = [];
  if ($type == 'node' && !empty($data['node']) && $data['node'] instanceof Node) {
    $node = $data['node'];
    foreach ($tokens as $name => $original) {
      if ($name == 'type_display') {
        $type = $node->getType();
        if (!in_array($type, hwjma_core_get_hw_content_types())) {
          $replacements[$original] = $type;
        }
        elseif (in_array($type, hwjma_core_get_book_chunk_types())) {
          $replacements[$original] = t('chapter');
        }
        else {
          switch ($type) {
            case HW_NODE_TYPE_ARTICLE:
              $replacements[$original] = t('article');
            break;
            case HW_NODE_TYPE_JOURNAL:
              $replacements[$original] = t('journal');
            break;
          }
        }
      }
    }
  }
  return $replacements;
}
